project_id = "tjjpzpqwemyfbgdaijee"

[functions.manage-users]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.fieldops]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.location-cleanup]
verify_jwt = false

[functions.gstin-lookup]
verify_jwt = false